### ISSUE TITLE
DAC8568 sometimes requires a power cycle to operate properly

### ISSUE THREAD

**Issue by ost-ing** [ostenning/dac8568#1]
- Likely the `CLR` and `SYNC` lines needs to be toggled on initialization to reset the device entirely

**Comment by robbietree8** [comment]
hi ostenning, you mean when do initialization, we should execute following command?

```
sync.set_high()
sync.set_low()
sync.set_high()
```

**Comment by ost-ing** [comment]
> hi ostenning, you mean when do initialization, we should execute following command?
> 
> ```
> sync.set_high()
> sync.set_low()
> sync.set_high()
> ```

Hi @robbietree8 , no you can just call `dac.reset()`, which will send a software reset message to the DAC, resetting all its registers back to default. This is now available in version 0.0.7.

Thanks!
